/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class Player {
    var points: String = "40"

    fun increaseScore(rivalPoints: String) {
        if (points == "Love") {
            points = "15"
        }
        else if(points == "15") {
            points = "30"
        }
        else if(points == "30"){
            points = "40"
        }
        else if(points == "40"){
            if (rivalPoints == "40"){
                points = "advantage"
            } else if(rivalPoints != "40" && rivalPoints != "advantage"){
                points = "WIN"
            } else if(rivalPoints == "advantage"){
                points = "40"
            }
        }
    }

}

fun main() {
    var player1 = Player()
    println(player1.points)
    player1.increaseScore("40")
    println(player1.points)
}
