/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class Player {
    var points: String = "Love"

    fun increaseScore() {
        if (points == "Love") {
            points = "15"
        }
        else if(points == "15") {
            points = "30"
        }
        else if(points == "30"){
            points = "40"
        }
        else if(points == "40"){
            points = "Win"
        }
    }

}

fun main() {
    var player1 = Player()
    println(player1.points)
    player1.increaseScore()
    println(player1.points)
}
